language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3

matrix:
  allow_failures:
    - python: pypy3

addons:
  apt:
    packages:
      - jq

before_install:
  - pip install --quiet --upgrade pip codecov

install:
  - make install

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: false
